[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
temp_project = "4Qno9PmRC5RV5yjaM8zPmTps3TH5T1PhLDqrDdqdYscH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
